version: '2'
services:

  postgres:
    image: postgres:9.5.2
    env_file: .env-postgres

  webserver:
    build:
      context: .
      dockerfile: Dockerfile

    depends_on: [postgres]
    links: [postgres]
    working_dir: /usr/src/app
    entrypoint: dockerize -wait tcp://postgres:5432 -timeout 20s
    command: ./docker/cmd-webserver.sh
    ports: ["8000:8000"]
    env_file: ./docker/.env
    restart: "always"
